name: prohmr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py37h89c1867_1
  - cudatoolkit=11.1.1=h6406543_8
  - decorator=5.0.5=pyhd3eb1b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=h6c09931_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.14=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.2=254
  - ipython=7.21.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=9.3.0=h2828fa1_18
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.41.0=h7f98852_0
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1k=h7f98852_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py37he98fc37_0
  - pip=21.0.1=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-opencv=3.4.2=py37hb342d67_1
  - pygments=2.8.1=pyhd3eb1b0_0
  - python=3.7.8=h6f2ec95_0_cpython
  - python_abi=3.7=1_cp37m
  - pytorch=1.8.1=py3.7_cuda11.1_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.1=py37
  - torchvision=0.2.2=py_3
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.2.5=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - argon2-cffi==20.1.0
    - astroid==2.5.2
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==20.3.0
    - bleach==3.3.0
    - cachetools==4.2.1
    - cffi==1.14.5
    - chardet==4.0.0
    - chumpy==0.70
    - cycler==0.10.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - freetype-py==2.2.0
    - fsspec==2021.5.0
    - future==0.18.2
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - grpcio==1.36.1
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==3.9.0
    - ipdb==0.13.7
    - ipykernel==5.5.5
    - ipywidgets==7.6.3
    - isort==5.8.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.6.0
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.0
    - mccabe==0.6.1
    - mistune==0.8.4
    - multidict==5.1.0
    - mypy==0.902
    - mypy-extensions==0.4.3
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5
    - git+https://github.com/nkolot/nflows.git
    - notebook==6.4.0
    - oauthlib==3.1.0
    - open3d-python==0.7.0.0
    - packaging==20.9
    - pandocfilters==1.4.3
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydeprecate==0.3.0
    - pyglet==1.5.15
    - pylint==2.7.2
    - pyopengl==3.1.0
    - pyparsing==3.0.0b2
    - pyrender==0.1.45
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytorch-lightning==1.3.6
    - pyyaml==5.3.1
    - pyzmq==22.1.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.6.2
    - send2trash==1.7.1
    - shapely==1.7.1
    - smplx==0.1.28
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.10.1
    - testpath==0.5.0
    - toml==0.10.2
    - torchgeometry==0.1.2
    - torchmetrics==0.2.0
    - tornado==6.1
    - tqdm==4.59.0
    - trimesh==3.9.10
    - typed-ast==1.4.2
    - umnn==1.68
    - urllib3==1.26.4
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wheel==0.36.2
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - yacs==0.1.8
    - yarl==1.6.3
    - zipp==3.4.1
